GET http://localhost:8080/customer

###

POST http://localhost:8080/customer
Content-Type: application/json

{
  "firstName": "Leon",
  "lastName": "Huber",
  "sex": "M"
}

###

POST http://localhost:8080/customer
Content-Type: application/json

{
  "firstName": "Sascha",
  "lastName": "Spindler",
  "sex": "M"
}

###

DELETE http://localhost:8080/customer/2
###