GET http://localhost:8080/api/customer

###

POST http://localhost:8080/api/customer
Content-Type: application/json

{
  "firstName": "Leon",
  "lastName": "Huber",
  "phoneNumber": "06608649288",
  "email": "leon187@gmail.com"
}

###

POST http://localhost:8080/api/customer
Content-Type: application/json

{
  "firstName": "Sascha",
  "lastName": "Spindler",
  "phoneNumber": "06708942473",
  "email": "s.spindler@outlook.com"
}

###

DELETE http://localhost:8080/customer
Content-Type: application/json

{
  "firstName": "Sascha",
  "lastName": "Spindler",
  "phoneNumber": "06708942473",
  "email": "s.spindler@outlook.com"
}

###